### PR TITLE
Add updates to CMS Editor Article Features

### LINKED ISSUE #25: As CMS editor, I can add / edit / save to draft / publish articles with robust features for promotion.
As CMS editor, 
I can add articles to any parent section or sub-section. **Article features which currently exist and should remain include:** 
- [x] Title
- [x] Feature Image
- [ ] Tags
- [x] Body (with pre-formatted features for lists, numbered lists, text, images, media, and page links)
- [x] Commenting Settings
- [ ] Recommended Articles
- ~~[ ] Recommended Section~~ (Edit by @dannyparsons: Not needed, see response from Laurie: Better to have a single recommendation and the editor can pick whether the link takes the user to a section or article)
- ~~[ ] Featuring in Homepage~~ (Edit by Danny: in discussion with Laurie agreed that this moves to a setting on the homepage instead of setting on each article)
- [x] Status (Publish, Draft, Unpublished)
- [x] Privacy
- [x] Edit Lock
- [x] Go Live Date Time / Unpublish Date Time

**Features which should be removed include:** 
- [x] Article > Content > Subtitle
- [x] Article > Promote > Feature in Latest
- [x] Article > Promote > Featuring in Section

**TBD Existing Features with Unknown Functionality**
-Social Media
-Tags for navigation
-Reaction Questions
- Article > Promote > Topic of the Day
- Article > Promote > Metadata
- Article > Promote > Common Page Configuration > Show in Menus
- Article > Promote > Common Page Configuration > Search Description
-
**Features which should be enhanced include:** 
- [ ] Style code should be able to be overwritten in the body 
- [x] Additional formatting options for body text including multiple header formats (right now, there's only H1 which makes text bold)
- [x] Adding a video or audio file should include an upload option, like as in images. Right now, you have to first load the files in the media section and then they can be accessed when editing pages)
- [x] Hyperlinking text to internal or external pages. Right now, inserting a page link results in the page title appearing. This is not editable. The editor should be able to link text such as "Learn more about vaccines." and link to the page "About Vaccines."
- [ ] The CMS editor should be able to insert an image and have the image appear as a hyperlink. 

**New Features Include:** 
- [ ] Add a body feature to embed a survey directly on the page - not necessarily at the bottom. 

**Nice to have Features (v3.0 beyond) include:** 
- [ ] Explore multi-column formatting for desktop view

### PR DESCRIPTION
**Pull request by ehmadzubair**
Fixes #25 

Changed done in this PR:
- Added Tags to Articles
- Added Tags on the Article Detail Page
- Added Recommended Articles in Article Admin
- Added (hyperlinked) Recommended Articles in the Article Detail Page
- Added Recommended Sections in Article Admin
- Added (hyperlinked) Recommended Sections in the Article Detail Page
- Added CSS for Recommended content

### CODE REVIEW

**Comment by ehmadzubair** [comment]
@istride Can you go through this whenever you have time?

cc: @dannyparsons

**Comment by istride** [comment]
I think the code is fine, I just have a problem with the purpose of these changes. I can understand the need for recommended articles, which I can see are currently used in v1 sites, and Laurie used it in the walkthrough video. However, tags and recommended sections were glossed over in the video, and I can't confirm whether they are used in v1.

@dannyparsons do we know how article tags are used or will be used?

Do we need to treat articles and sections separately, or can we lump them together and make the order in which they are presented an editorial decision (like the homepage)?

Would it be beneficial to be able to link to other types of content from the 'recommended' section, such as surveys/polls/quizzes, or an external link?

**Comment by ehmadzubair** [comment]
@istride I think recommended articles have to be shown with their image/title. Same for surveys/polls/quizzes (i think). External link wouldn't let us do that easily. Thoughts?

**Comment by dannyparsons** [comment]
Going by #25 description, tags and recommended sections have been noted to keep - I don't see Recommended Sections having any effect in the v1 demo site and I can't find any examples on live sites, I've queried this on #25 and whether recommended articles/section could be together. I think tags are useful to have, even if not used much currently.

I don't think recommended surveys/polls/quizzes would be needed as these would be featured in the body as I understand from the current use.

**Comment by ehmadzubair** [comment]
Okay, this PR can wait till Laurie replies on #25

**Comment by dannyparsons** [comment]
Sorry I forgot to update on this, I added the response from Laurie https://github.com/unicef/iogt/issues/25#issuecomment-851390241

**Comment by istride** [comment]
@ehmadzubair  I think this PR is waiting for more work to be done on it. Can this be completed before any new task is started?

**Comment by ehmadzubair** [comment]
@istride There wasn't anything left to be done in this. The current functionality (recommended articles and recommended sections in Article Admin) is consistent with what Laurie is expecting.

Resolving the conflicts however was a long exercise :(. This PR can be merged now

cc: @dannyparsons

**Pull request merged**
