### PR TITLE
Fixed registration_survey to display the localized version of the survey

### LINKED ISSUE #182: Custom registration survey shows correct language version of the survey
The registration survey that is selected in Site Settings should show the translated version of that survey when the user is viewing the site on with a different language.

### PR DESCRIPTION
**Pull request by ehmadzubair**
Fixes #182

### CODE REVIEW

**Comment by sheralim012** [comment]
👍🏽

**Comment by geoo89** [comment]
When exporting users, only those who filled out the default (English) survey have their survey responses in the output spreadsheet., while the responses are missing for users who filled out a translated sheet. This should be fixed.

**Comment by sheralim012** [comment]
looking into it

**Comment by geoo89** [comment]
I accidentally merged this in, and I don't want to do a force push to revert it.
Please add the fix with user export in a separate PR.

**Pull request merged**
