### PR TITLE
adds rendering of video thumbnail

### LINKED ISSUE #1187: Video Thumbnails Not Appearing
When a thumbnail is loaded on a video, it does not appear on the site. 

Example: 
[This video](https://www.internetofgoodthings.org/admin/media/edit/20/) has a thumbnail image loaded
[Here is the video on the site](https://www.internetofgoodthings.org/en/sections/covid-19-frontline-worker-training/course-1-covid-19-basics/11-countering-misinformation-surrounding-covid-19/), note that it appears without the thumbnail.

### PR DESCRIPTION
**Pull request by sheralim012**
Closes #1187 

- render video thumbnail if available

### CODE REVIEW

**Comment by geoo89** [comment]
@edmoss345

**Comment by edmoss345** [comment]
Tested by adding a sample video with a thumbnail and was still not getting any thumbnail in the page view, see images below.

image

image

image

**Comment by sheralim012** [comment]
@edmoss345 could you check now, there was a double quote issue with the media URL and I have fixed it

**Comment by edmoss345** [comment]
lgtm, thumbnail is now showing

image

**Pull request merged**
