### PR TITLE
Add user registration, login and update views

### PR DESCRIPTION
**Pull request by ikonitas**
### Source 
https://github.com/unicef/iogt/issues/55

### Description
- Add a wagtail page called `UserRegistrationPage` where user can add extra questions to the registration process
- Add customise `User` model
- Add login view
- Add user profile view
- Add update user view
- Add tests

### How to test
1. Drop SQLite database
2. Do fresh migrations
3. Go to wagtail admin and create with custom questions `UserRegistrationPage` (the only one this page can be created per site) 
4. Check if user registration works
5. Check login `/accounts/login/`
6. Check profile update `/accounts/update/`
7. Run tests `./manage.py test --keepdb --settings=iogt.settings.testing`

### CODE REVIEW

**Comment by istride** [comment]
I've reviewed the PR, and had no trouble testing the functionality. I appreciated the instructions.

I do have a few concerns though:

* front-end is a bit too basic; I was not expecting something beautiful, but at least presentable
* missing links to log in, log out and register
* once registered, I was not able to change anything on my profile apart from my password
* the key for additional data fields derived from its label - perhaps they should be specified separately
* additional data caused an error during registration (more below)

I created a registration page that included an additional 'date of birth' field, which I set up as a date. On the registration page, I filled in the form and entered a date in 'dd/mm/yyyy' format. An error occured.

**Comment by ikonitas** [comment]
> I've reviewed the PR, and had no trouble testing the functionality. I appreciated the instructions.
> 
> I do have a few concerns though:
> 
> * front-end is a bit too basic; I was not expecting something beautiful, but at least presentable
> * missing links to log in, log out and register
> * once registered, I was not able to change anything on my profile apart from my password
> * the key for additional data fields derived from its label - perhaps they should be specified separately
> * additional data caused an error during registration (more below)
> 
> I created a registration page that included an additional 'date of birth' field, which I set up as a date. On the registration page, I filled in the form and entered a date in 'dd/mm/yyyy' format. An error occured.

Thanks for checking this out!

1. I added basic styling
2. I added those missing links so if the registration page doesn't exist won't be shown in FE
3. Please try again, I also added some feedback message using `django.contrib.messages`
4. Fixed
5. I forgot to add `DjangoJsonEnoder` should work fine now.

Any questions please ask.

**Comment by istride** [comment]
1. It's very important that users be able to amend their profile, including any additional data - this is not possible at the moment
2. When a user logs in/out they ought to be taken to the home page
3. A logged in user should be able to go their profile via a link in the header
4. Date inputs on the registration form must support the user to enter correct dates e.g. a date widget, or dropdowns.
5. Would be nice to see more testing of 'unhappy' paths

**Comment by ikonitas** [comment]
@istride thanks for the feedback, do you know what date picker library you prefer to use it?
I found two open-source libs:

https://flatpickr.js.org/examples/
https://www.jonthornton.com/Datepair.js/

**Pull request closed without merging**
