### PR TITLE
show warning of facebook free basics

### LINKED ISSUE #542: Warning when adding content incompatible with Facebook Free Basics
As a PLATFORM ADMINISTRATOR I want to be reminded when content I'm adding to the site is outside of Facebook Free Basics specifications.

This can be
1. Video
2. Large images (> 200KB)
3. Documents (which will be linked)

Should be a small notification, eg helptext, in red.

Full guidelines are here:
https://developers.facebook.com/docs/internet-org/platform-technical-guidelines
https://developers.facebook.com/docs/internet-org/how-to-submit

### PR DESCRIPTION
**Pull request by sheralim012**
fixes #542 

- show warning on videos add/edit
- show warning on images larger than 200kb add/edit
- show warning on documents larger than 200kb add/edit

### CODE REVIEW

**Comment by geoo89** [comment]
image

Similarly you can add a media block to an article, and upload audio/video there.

These cases should be covered as well.

**Comment by sheralim012** [comment]
> I think there are some ways of uploading media which are not covered yet:
> When editing a page, and e.g. adding a lead image or an image block for an article, you can either select from the image bank or upload a new one. If you upload a new one in this dialog, no warning is shown

try to clear cache, as this is already handled

> 
> image
> 
> Similarly you can add a media block to an article, and upload audio/video there.

handled this case too.

> 
> These cases should be covered as well.

**Comment by geoo89** [comment]
Thanks, the messages are there now everywhere.

In #542 Chris clarified that documents are not allowed at all for facebook free basics, so please adjust accordingly.

Also minor issue, but sometimes the limit is displayed as 204800KB rather than 200 KB in the error message?

**Comment by sheralim012** [comment]
> Thanks, the messages are there now everywhere.
> 
> In #542 Chris clarified that documents are not allowed at all for facebook free basics, so please adjust accordingly.

done

> Also minor issue, but sometimes the limit is displayed as 204800KB rather than 200 KB in the error message?

done

**Pull request merged**
