### PR TITLE
:lipstick: Fixed logo and scaling issues

### LINKED ISSUE #609: Logo and image scaling issues
1024 and above width: logo is clear and article image is clear
image

768 to 320 width: logo is pixelated and article image is clear
image

320 width: logo is pixelated and article image is pixelated
image

I'm noticing that the logo is stored as a 60px width image, even though it's always displayed wider than 60px.

### PR DESCRIPTION
**Pull request by ehmadzubair**
Closes #609

### CODE REVIEW

**Comment by ehmadzubair** [comment]
@sheralim012 we need to update this in #957 as well.

**Comment by geoo89** [comment]
I merged #957, you can update this branch and add the change there as well.

**Comment by geoo89** [comment]
Could you quickly cross-check as well if any of the code changes from https://github.com/unicef/iogt/pull/620/files are relevant here as well? (I don't remember if e.g. article card in sections and recommended content in articles use the same rendering logic now.)

**Comment by geoo89** [comment]
#992 proposes to change the maximum width of the central column to be the same as the outer two columns in desktop view. Reason is that banners and other header images take up a lot of vertical screen estate. (The main use case is mobile view anyway, and this would reflect this a bit more closely as well I assume.)

If so, we should probably change the image widths for full-width (and half-width) images correspondingly.

**Comment by sheralim012** [comment]
addressed changes for section featured content #957

**Comment by sheralim012** [comment]
#992 changes are addressed in this PR

**Comment by sheralim012** [comment]
@geoo89 I have unapplied #992 changes from this PR

**Comment by geoo89** [comment]
The links in section cards don't work anymore: When I click onto a section card, rather than taking me to the child section, it just takes me to the page I'm currently on.

Can we change the image quality from 560/280 to 360/180 (reasons see #1030)?

Is it possible to also apply this to images within paragraphs, or is this trickier? If yes, I can make a separate issue.

**Comment by sheralim012** [comment]
@geoo89 
- fixed section card URL
- updates sizes to 360/180

**Pull request merged**
