### PR TITLE
Fixed heading size

### LINKED ISSUE #390: Header content block text is not larger than paragraph content block text
Input

image

Live article

image

### PR DESCRIPTION
**Pull request by ehmadzubair**
Fixes #390

### CODE REVIEW

**Comment by geoo89** [comment]
It looks like this for me now:
image

So the heading and the title are the same size now. Could you choose a size that is in between the title and the paragraph size?

**Comment by azahid89** [comment]
@geoo89 The title is basically an H1 tag (in the figma design). H2, H3 and H4  are available in the paragraph field. Now we can either increase the Title size or decrease the Heading size. Please note this would mean the heading will not be a H1 tag but a custom div.

**Comment by geoo89** [comment]
I just tried inserting a H2 into a paragraph, and it appears that it is also the same size as the title:
image

From what I see in the page source, the title is H1, the heading is a custom div, and a H2 in a paragraph is a H2, so at least in principle there shouldn't be an issue giving each a different size. But maybe all of them being the same size is not a problem. Let me ask at tomorrow's meeting and I'll get back to you.

**Comment by geoo89** [comment]
This is good for now. I created #464 to check back whether all headings having the same size is want we want, design-wise.

**Pull request merged**
