### PR TITLE
Fixes for issues #601, #602.

### LINKED ISSUE #601: Add help text to External Link dialogue
When users add External Links:

image

Add a help text in red below the URL:

> If you are linking back to a URL on your own IoGT site, be sure to remove the domain and everything before it. For example  "http://sd.goodinternet.org/url/" should instead be "/url/".

This will prevent issues when platforms are available at two urls, eg ec.goodinternet.org and internetdelascosasbuenas.org.

### LINKED ISSUE #602: Add help text when editing Flat Menu handle
image

Should include help text

> The handle must be written in this format "[language]_[menu name of your choice]". For example, "en_menu1". If you would like the menu to be visible on the website you must add "_live" to the end, eg "en_menu1_live". Only one menu per language can be visible at one time.

### PR DESCRIPTION
**Pull request by mbilalhameed**
fixes #601 
fixes #602

### CODE REVIEW

**Comment by mbilalhameed** [comment]
> It seems like the migrations are messed up. When trying to run them on a DB which has existing flat menus, the migration crashes:
> 
> ```
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 245, in handle
>     fake_initial=fake_initial,
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 229, in apply_migration
>     migration_recorded = True
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 35, in __exit__
>     self.connection.check_constraints()
>   File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 348, in check_constraints
>     bad_value, referenced_table_name, referenced_column_name
> django.db.utils.IntegrityError: The row in table 'home_iogtflatmenuitem' with primary key '7' has an invalid foreign key: home_iogtflatmenuitem.menu_id contains a value '1' that does not have a corresponding value in home_iogtflatmenu.id.
> ```

I have changed the `IogtFlatMenu` model, migrations are working fine now  could you check again

**Comment by geoo89** [comment]
The help text for #602 appears in the flat menu admin panel.
However, the help texts requested in #601 don't seem to appear (in either the flat menu nor the external link menu when adding an external link to e.g. a paragraph block).

Also, please undo the rename from `home/migrations/0022_merge_20211020_0850.py` to `home/migrations/0022_merge_20211101_1412.py`, as it clashes with existing migrations (maybe best to rebase your PR on top of develop to see it in the context of the most recent changes).

**Comment by geoo89** [comment]
The help text now appears to show only in the first menu item of the flat menu, but not for further ones. Also, it doesn't appear for new menu items if you add them.

It also doesn't seem to display when in article, I add a paragraph and in this paragraph I add an external link.

**Comment by geoo89** [comment]
Thanks! This turned out be more complicated than expected.

**Comment by cbunicef** [comment]
Thanks for seeing this through to completion!

**Pull request merged**
