### PR TITLE
makes skip logic field nullable and fix multi-step quiz submission

### PR DESCRIPTION
**Pull request by sheralim012**
* Fixed issue of required skip logic field for text type fields (fields without any choice)
* Fixed issue with multi-step quiz/survey submission

### CODE REVIEW

**Comment by ehmadzubair** [comment]
👍🏼

**Comment by sheralim012** [comment]
@geoo89 check and let me know.

**Comment by geoo89** [comment]
On a multipage quizzes, I now score 0 (at the top) regardless of how many questions I get right.

Page now crashes for me single page quizzes, see below:

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/fr/sections/questionnaire-testing/sample-quiz/?back_url=/fr/sections/questionnaire-testing/sample-quiz/&form_length=4

Django Version: 3.1.11
Python Version: 3.6.9
Installed Applications:
['home',
 'search',
 'iogt_users',
 'comments',
 'iogt_content_migration',
 'questionnaires',
 'messaging',
 'django.contrib.humanize',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailmedia',
 'wagtailmarkdown',
 'wagtail_transfer',
 'wagtailsvg',
 'wagtail.contrib.settings',
 'django_comments_xtd',
 'django_comments',
 'modelcluster',
 'taggit',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'sass_processor',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'iogt_users.middlewares.RegistrationSurveyRedirectMiddleware',
 'external_links.middleware.RewriteExternalLinksMiddleware']


Template error:
In template /data/idems/iogt/iogt/iogt/templates/base.html, error at line 14
   'str' object has no attribute 'get'
   4 : <!DOCTYPE html>
   5 : <html class="no-js" lang="en">
   6 : <head>
   7 :     <script async src="https://www.googletagmanager.com/gtag/js?id={{ settings.home.SiteSettings.local_ga_tracking_code }}"></script>
   8 :     <script>
   9 :         window.dataLayer = window.dataLayer || [];
   10 :         function gtag(){window.dataLayer.push(arguments);}
   11 :         gtag('js', new Date());
   12 :         gtag('config', '{{ settings.home.SiteSettings.local_ga_tag_manager }}');
   13 :         gtag('config', '{{ settings.home.SiteSettings.global_ga_tag_manager }}');
   14 :         gtag('confi g', '{{ settings.home.SiteSettings.lo cal_ga_tracking_code }}');
   15 :         gtag('config', '{{ settings.home.SiteSettings.global_ga_tracking_code }}');
   16 :     </script>
   17 :     <meta charset="utf-8"/>
   18 :     <title>
   19 :         {% block title %}
   20 :             {% if self.seo_title %}{{ self.seo_title }}{% else %}
   21 :                 {{ self.title }}{% endif %}
   22 :         {% endblock %}
   23 :         {% block title_suffix %}
   24 :             {% with self.get_site.site_name as site_name %}


Traceback (most recent call last):
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/data/idems/iogt/iogt_venv/lib/python3.6/site-packages/django/template/base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "/data/idems/iogt/iogt/questionnaires/templatetags/questionnaires_tags.py", line 102, in get_item
    return dictionary.get(key)

Exception Type: AttributeError at /fr/sections/questionnaire-testing/sample-quiz/
Exception Value: 'str' object has no attribute 'get'

```

**Comment by sheralim012** [comment]
@geoo89 I pushed a fix, check and let me know if any change is required.

**Pull request merged**
