### PR TITLE
Community moderators can now add Canned Responses

### LINKED ISSUE #37: Community Moderator user group allows enrolled front-end users to assist with comment moderation.
They will have the ability to delete or respond to users with canned responses (developed by CMS editors on backend). In their profile, they can view the total number of comments moderated (total and in the last week).

### PR DESCRIPTION
**Pull request by ehmadzubair**
Closes #37 

### Testing instructions
- Add canned responses from the admin site
- Login as moderator
- See the Canned Responses dropdown in the comment form

### CODE REVIEW

**Comment by geoo89** [comment]
Could you create (e.g. add it to create_initial_content) a Community Moderator group that has the appropriate permissions?

I tried to create a group that can moderate comments without admin access, but pressing 'Add canned response' button then redirects me to the admin login: `http://localhost:8000/admin/login/?next=/admin/comments/comment/process-canned-response`
Permissions I set for my group: 
- Canned Repose: add, edit, delete
- Other permissions
    - Can moderate comments
    - Can view canned response

Also, the dropdown list is super long when the canned response text is long:
canned_response
I think it's better to only display the title (and ideally wrap its text if it is still too long, though that should be unlikely to happen?). If it's simple, also add CSS for the dropdown (though at least it's only moderator facing, not for the average user); but if that's tricky defer it to a future issue.

**Comment by sheralim012** [comment]
@geoo89 addressed changes
- long canned response text will be truncated at a length of 50 or greater
- create initial data command will give moderator group permission to comment canned response
- user added to moderator group will be able to post canned responses
- user added to any group with permission "Can moderate comments" will be able to post canned responses
- updated CSS for canned response dropdown
- be sure to set the correct site hostname and port in the settings

**Comment by geoo89** [comment]
> I tried to create a group that can moderate comments without admin access, but pressing 'Add canned response' button then redirects me to the admin login: http://localhost:8000/admin/login/?next=/admin/comments/comment/process-canned-response

This issue still persists. If I'm adding a canned response as admin, there are no issues, but if I'm a community moderator without admin access, the above issue occurs.

**Comment by sheralim012** [comment]
@geoo89 pushed a fix for it

**Pull request merged**
