### PR TITLE
update prompt text size

### PR DESCRIPTION
**Pull request by ehmadzubair**

### CODE REVIEW

**Comment by geoo89** [comment]
It looks like this for me now:
image

I can't see any change in the prompt text size (highlighted in red).

**Comment by ehmadzubair** [comment]
@geoo89 I have tested this on my local. Is this what you're looking for? If yes, can you try force refreshing?

Screenshot 2021-08-11 at 3 57 23 PM

**Comment by geoo89** [comment]
Ah, it appears that for embedded questionnaires the text has increased, but not for standalone questionnaires.

**Comment by ehmadzubair** [comment]
@geoo89 can you test this now?

**Pull request merged**
