### PR TITLE
Update wagtail version v2.15 LTS

### LINKED ISSUE #515: After deleting a section content, browser returns to the same URL which now gives a 404
Error:

<html>
<body>
<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px 0px 0.4em; font-weight: normal;">Page not found<span> </span><span style="padding: 0px; margin: 0px; font-size: 15.6px; color: rgb(102, 102, 102); font-weight: normal;">(404)</span></h1>

Request Method: | GET
-- | --
http://central.iogt.site/en/admin/pages/994/
wagtail.core.views.serve

</div><div id="info" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(246, 246, 246); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">Using the URLconf defined in<span> </span><code style="padding: 0px; margin: 0px;">iogt.urls</code>, Django tried these URL patterns, in this order:</p><ol style="padding: 0px; margin: 0.5em 4em;"><li style="padding: 0px; margin: 0px; font-family: monospace;">django-admin/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">documents/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ logout_hack_view [name='logout_redirect']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ search/ [name='search']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ users/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ accounts/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ comments/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">sw.js [name='sw.js']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ external-link/ [name='external-link']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ messaging/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">wagtail-transfer/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">sitemap/ [name='sitemap']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">manifest.webmanifest [name='manifest']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">^static/(?P&lt;path&gt;.*)$</li><li style="padding: 0px; margin: 0px; font-family: monospace;">^media/(?P&lt;path&gt;.*)$</li><li style="padding: 0px; margin: 0px; font-family: monospace;">__debug__/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ _util/authenticate_with_password/&lt;int:page_view_restriction_id&gt;/&lt;int:page_id&gt;/ [name='wagtailcore_authenticate_with_password']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ _util/login/ [name='wagtailcore_login']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ ^((?:[\w\-]+/)*)$ [name='wagtail_serve']</li></ol><p style="padding: 0px; margin: 0px;">The current path,<span> </span><code style="padding: 0px; margin: 0px;">en/admin/pages/994/</code>, matched the last one.</p></div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 0px none; background: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px;">False</code>, and Django will display a standard 404 page.</p></div>
</body>
</html>

### LINKED ISSUE #1123: Survey's Questions Preview
Added to a survey questions that required date of birth and email address. When looking at the preview, before publishing the content, the questions won't display. Only when the page is published the questions will display.

image

### LINKED ISSUE #1290: Error when translating a page - MultipleObjectsReturned, TranslationSource
To reproduce this bug:

1) Create a site with at least 1 page, in the English locale
1) Add a locale (L1), don't synchronise
1) Add another locale (L2), don't synchronise
1) Translate the English page into L1
1) Translate the L1 page to L2
1) Boom!

There is a [very similar issue][1] logged in the wagtail-localize project. Potentially, this problem will not be resolved until it is resolved in wagtail_localize. Nevertheless, we would still want to know what can be done to recover from this bug if/when it happens, and to prevent it from happening in the first place.

Stacktrace:
```
Traceback (most recent call last):
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/views/generic.py", line 60, in run_hook
    result = fn(*args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail_localize/wagtail_hooks.py", line 259, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail_localize/views/edit_translation.py", line 819, in edit_translation
    locale_id=TranslationSource.objects.get(
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /admin/pages/39/edit/
Exception Value: get() returned more than one TranslationSource -- it returned 2!
```

[1]: https://github.com/wagtail/wagtail-localize/issues/547

### LINKED ISSUE #1367: Cannot edit Page after translating - an isolated case as far as we are aware
Steps which were taken before the error was identified:
1. A selection of English content was imported from Global to SA
2. A sub-selection of English content had translation started to Bengali: https://sa.iogt.site/admin/pages/1338/

The error:
1. One of the translated Pages cannot be edited, due to server error: https://sa.iogt.site/admin/pages/1405/edit/

Other symptoms discovered during troubleshooting:
1. The affected Page can be copied underneath the same Parent. The copy of the Page can be edited. When editing we can see the appropriate Title, Slug, and time of last edit. However when viewing the list of Pages under the Parent, the Page shows the same Title and time of last edit as the original Page
2. Other Pages under the same Parent which were translated can be edited, and when they are copied the list of Pages under the Parent shows the Title and last time of edit for the _copy_ not the _original_. We think this is the designed behavior

@ChrisMarsh82 @istride @sheralim012 as discussed on our call today

@lauriemarkle FYI

### LINKED ISSUE #1373: Update wagtail version
Current version: 2.11 (lts)

Update version: 2.15 (lts)

### LINKED ISSUE #1374: Question selector in skip logic is showing undefined instead of question label
Screenshot 2022-08-17 at 1 19 08 PM

### PR DESCRIPTION
**Pull request by sheralim012**
Closes #1373 
Closes #1290 
Closes #515 
Closes #1367 
Closes #1374
Closes #1123 

- updates wagtail version to 2.15 lts
- updates wagtail localize version to 1.2.1
- following are the issues introduced after updating
  - server and client side skip logic stream block implementation (see [here](https://docs.wagtail.org/en/stable/releases/2.13.html#new-client-side-implementation-for-custom-streamfield-blocks))
  - making skip logic field non-required (see [here](https://docs.wagtail.org/en/stable/releases/2.13.html#updated-handling-of-non-required-streamfields))
  - stream field data access and modification (see [here](https://docs.wagtail.org/en/stable/releases/2.12.html#stream-data-on-streamfield-values-is-deprecated))

affected areas:
- skip logic in admin panel
- questionnaires apis
- page-tree API for caching
- content migration from v1
- page translation from a translation
- deleting parent page

### CODE REVIEW

**Review by istride — APPROVED** [review]
Waiting for IoGT v2.1.0 to be released before merging.

**Comment by cbunicef** [comment]
@sheralim012 We lost a number of our "Other Permissions" items in Groups.

This is from global, which is on 2.11.9:

https://www.internetofgoodthings.org/admin/groups/5/

image

This is from sandbox on 2.15.6:

https://sandbox.iogt.site/admin/groups/5/

image

**Comment by sheralim012** [comment]
Looking into it

**Comment by Alihassanc5** [comment]
> @sheralim012 We lost a number of our "Other Permissions" items in Groups.
> 
> This is from global, which is on 2.11.9:
> 
> https://www.internetofgoodthings.org/admin/groups/5/
> 
> image
> 
> This is from sandbox on 2.15.6:
> 
> https://sandbox.iogt.site/admin/groups/5/
> 
> image
> 
> Specifically I was looking for "Can moderate comments"

@cbunicef this issue is fixed in #1475

**Pull request merged**
