### PR TITLE
display landing for questionnaires

### LINKED ISSUE #471: Display of survey/poll/quiz if submission is prevented
There are different cases this can happen and need to have the correct display:

1. If a survey does not allow multiple submissions and a submission has already been made then when you go to the page it should show the title, the description and the text "You have already completed this survey". See v1 implementation below.

image

2. If a poll or quiz does not allow multiple submissions and a submission has already been made then when you go to the page it should _additionally_ show the results page for that poll/quiz. (For the poll only if the option "Show results" is enabled in Wagtail.)

3. If a survey/poll/quiz requires a login and a user is not logged in then when you go to the page it should show the title, the description and a button which says "Log in to participate" which takes the user to the login page. Once logged in, the user is redirected back to the page. See v1 implementation below.

image

In each case, ideally the same display should be shown when the survey/poll/quiz is embedded within an article.

### PR DESCRIPTION
**Pull request by sheralim012**
fixes #471 

- for survey if already submitted without allow multiple submissions show already submitted text
- for anonymous user if login is required show button for it and on login go back to poll/survey
- for poll if already submitted without allow multiple submissions show results

### CODE REVIEW

**Comment by ehmadzubair** [comment]
👍🏼

**Comment by geoo89** [comment]
- Also make this work for questionnaires embedded in a section/article

Single-submission
- Also display "You have already completed this survey." for polls and quizzes (for polls in addition to the results). Note: The wording "survey" rather than "poll/quiz" is deliberate here due to missing translations

Non-anon submission
- Also display "Log in to participate" for quizzes
- Use the same styling for "Log in to participate" that the submit button would use.

**Comment by sheralim012** [comment]
> * Also make this work for questionnaires embedded in a section/article

done

> Single-submission
> 
> * Also display "You have already completed this survey." for polls and quizzes (for polls in addition to the results). Note: The wording "survey" rather than "poll/quiz" is deliberate here due to missing translations

done

> Non-anon submission
> 
> * Also display "Log in to participate" for quizzes
> * Use the same styling for "Log in to participate" that the submit button would use.

done

**Comment by geoo89** [comment]
- "You have already completed this survey." is now displayed for questionnaires embedded in articles, but not for direct display questionnaires.
- For polls embedded in articles, the results aren't shown if you've already completed the poll before.

**Comment by sheralim012** [comment]
> * "You have already completed this survey." is now displayed for questionnaires embedded in articles, but not for direct display questionnaires.

done

> * For polls embedded in articles, the results aren't shown if you've already completed the poll before.

done

**Comment by geoo89** [comment]
- For direct display **surveys**, the "YOU HAVE ALREADY COMPLETED THIS SURVEY." text isn't displayed (you can still see the survey questions).
- For embedded/direct display polls, the % sign is missing from the results (when "Result as percentage" is enabled).

**Comment by sheralim012** [comment]
> * For direct display **surveys**, the "YOU HAVE ALREADY COMPLETED THIS SURVEY." text isn't displayed (you can still see the survey questions).

showing "YOU HAVE ALREADY COMPLETED THIS SURVEY." for me, could you share your DB with me.

> * For embedded/direct display polls, the % sign is missing from the results (when "Result as percentage" is enabled).

done

**Comment by sheralim012** [comment]
> > * For direct display **surveys**, the "YOU HAVE ALREADY COMPLETED THIS SURVEY." text isn't displayed (you can still see the survey questions).
> 
> showing "YOU HAVE ALREADY COMPLETED THIS SURVEY." for me, could you share your DB with me.
> 

fixed this edge case too.

**Pull request merged**
